/* eslint-disable no-console */
const csvParse =
  /** @type {(input: string|Buffer, options: object) => Array} */
  (require("csv-parse/lib/sync"));
const fs = require("fs");
const path = require("path");

const csv = fs.readFileSync(path.join(__dirname, "AusterityWiki.csv"));
const table = csvParse(csv, {columns: h => h.map(c => c.toLowerCase())});
const rows = table.reduce((o, row) => {
  const name = row.name.replace(/[ ']/g, "");
  if (o[name]) {
    throw new Error(`${row.name} overlaps with ${o[name].name}`);
  }
  o[name] = row;
  return o;
}, {});

console.log("// This file was generated by generateCardsTable.js ");
console.log("// prettier-ignore");
console.log("module.exports = ");
console.log(JSON.stringify(rows, null, 2));
console.log(";");
